Feature symfony7 update
excelwebzone/EWZRecaptchaBundle pull request #306
Opened 2023-12-29 18:14 UTC by snipershady

Now compliant with Symfony 7.0

2023-12-29 18:18 UTC, excelwebzone commented
@snipershady please run the check and fix the issues before I can merge it. Thanks.

2023-12-29 18:38 UTC, snipershady commented
> @snipershady please run the check and fix the issues before I can merge it. Thanks.

Michael I've fixed, now all PHPunit tests are succesfully completed

`OK (23 tests, 99 assertions)`

2023-12-29 18:41 UTC, excelwebzone commented
Nope, still not passing.. https://github.com/excelwebzone/EWZRecaptchaBundle/actions/runs/7359000381/job/20033164385?pr=306

2023-12-29 18:42 UTC, snipershady commented
Oo I forgot what php < 7.3 does not support strict type declartion for attributes...

let me fix it again with legacy compatibility

2023-12-29 18:51 UTC, excelwebzone commented
Still not working.. https://github.com/excelwebzone/EWZRecaptchaBundle/actions/runs/7359071392/job/20033299482?pr=306

2023-12-29 18:53 UTC, snipershady commented
> Still not working.. https://github.com/excelwebzone/EWZRecaptchaBundle/actions/runs/7359071392/job/20033299482?pr=306

because we cannot run test with Symfony 7.0 on PHP < 8.2

I think we should create a new branch of the package with PHP 8.2 strict compatibility, if we want to run this bundle on symfony 7.

what do you think about?

2023-12-29 19:10 UTC, snipershady commented
I've updated the arraylist of version and tests for CI

:crossed_fingers:

2023-12-30 02:05 UTC, excelwebzone commented
Sorry. Still not working.. Right now I don't have a lot of time to spend on this.. but once I'd I will try to fix your PR

2023-12-30 09:44 UTC, snipershady commented
> Sorry. Still not working.. Right now I don't have a lot of time to spend on this.. but once I'd I will try to fix your PR

I've rollback to some backward legacy compatibility for the deprecated PHP version 
let's figure it out if this is the final shot

2023-12-30 15:00 UTC, excelwebzone commented
Still not working. I don't think you can convert to PHP7 unless you remove all previous versions. Sorry :-(

2023-12-30 17:18 UTC, snipershady commented
> Still not working. I don't think you can convert to PHP7 unless you remove all previous versions. Sorry :-(

it is on you, I do not want to change compatibilty of the package with legacy versions, but it seams to be necessary.
I've done a fork only with current version of PHP and Symfony to upgrade my symfony softwares, and it works fine. If you accept to change the backward compatibility with ancient php version and ancient symfony version, I will be glad to prepare a new PR.

2024-01-09 07:50 UTC, Seb33300 requested changes

2024-01-09 07:50 UTC, Seb33300 commented on src/Validator/Constraints/IsTrue.php
> +    public function getTargets(): array|string
Union Type is not supported by PHP 7.x, please remove it

2024-01-09 07:50 UTC, Seb33300 commented on src/Validator/Constraints/IsTrueValidator.php
> +    protected bool $verifyHost;
Typed properties are supported by PHP 7.4+
You need to remove `bool` to keep compatibility with lower PHP version

2024-01-09 07:50 UTC, Seb33300 commented on src/DependencyInjection/EWZRecaptchaExtension.php
> +    private function getTwigFormResources(ContainerBuilder $container): array|string|false
Union types to remove

2024-01-09 07:50 UTC, Seb33300 commented on src/Form/Type/AbstractEWZRecaptchaType.php
> +    protected string $recaptchaApiServer;
Please removes all property types from that class

2024-01-09 07:50 UTC, Seb33300 commented on src/Resources/views/Form/ewz_recaptcha_widget.html.twig
> +              let recaptchaSubmitEvent = document.createEvent('Event');
This is unrelated to Symfony 7

2024-01-09 15:13 UTC, Seb33300 commented
This PR can be closed

2026-02-12 16:09 UTC, closed without merging